### ISSUE TITLE
Update nightly-build workflow so that it does not report error if nightly build already exists

### ISSUE THREAD

**Issue by lindong28** [alibaba/feathub#10]
Currently nightly build workflow can be triggered either manually or triggered by the daily schedule. If it has been triggered manually, the daily scheduled execution will fail due to "File already exists" error, which leads to unnecessary inconvenience for developers.

It might be better to use avoid this situation by using Test PyPI to perform and check the upload first. See https://pypi.org/help/#file-name-reuse for more detail.

**Comment by Sxnan** [comment]
Fixed by #16
