### ISSUE TITLE
The QR code has expired，how to connect you ？

### ISSUE THREAD

**Issue by VencentZhou** [alibaba/feathub#130]
The QR code has expired，I want to join you and learn together，update the QR please，thanks!

**Comment by VencentZhou** [comment]
im in china

**Comment by lindong28** [comment]
@VencentZhou Sorry for the late reply. The QR code has been updated now. Can you try again?

**Comment by VencentZhou** [comment]
> @VencentZhou Sorry for the late reply. The QR code has been updated now. Can you try again?

提示系统繁忙加不进去，“该群为内部群”

**Comment by lindong28** [comment]
@VencentZhou 这个群是属于“Apache Flink China”社区的，按道理是社区的参与者都可以申请并自动加入的。所以“内部群”应该不是影响自助加入。

我看到昨天下午1点有人是通过二维码加入这个群的，感觉这个二维码应该是可以用的。不过我自己没有第二个钉钉好，无法直接测试功能。

我估计昨天钉钉系统不稳定，是因为“系统繁忙”所以没有能加入。你可以再试试吗？如果还是不能用的话，请加我的钉钉号lindong28吧。
